TestingProject.WebApp/Models/ErrorViewModel.cs
namespace TestingProject.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestingProject.WebApp/Controllers/AttachmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.IO;
using System.Threading.Tasks;
using TestingProject.DTOs;
using TestingProject.IServices;

namespace TestingProject.WebApp.Controllers
{
    public class AttachmentController : Controller
    {
        private readonly IAttachmentService _attachment;
        private readonly IConfiguration _configuration;
        public AttachmentController(IAttachmentService attachment, IConfiguration configuration)
        {
            _attachment = attachment;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddFile(IFormFile files)
        {
            string path = _configuration.GetConnectionString("Path") + files.FileName;
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await files.CopyToAsync(stream);
            }
            return Ok();
        }

        public async Task<IActionResult> Create(AttachmentDTO attachment)
        {
            var Id = await _attachment.Create(attachment);
            return Ok(Id);
        }
    }
}

TestingProject.WebApp/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using TestingProject.DTOs;
using TestingProject.IServices;

namespace TestingProject.WebApp.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _car;
        private readonly IDateTestService _dateTest;
        public CarController(ICarService car, IDateTestService dateTest)
        {
            _car = car;
            _dateTest = dateTest;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _car.Get());
        }

        public async Task<IActionResult> AddEditCar(CarDTO model)
        {
            ViewData["DateList"] = await _dateTest.Get();
            ViewData["CarList"] = await _car.Get();
            ViewData["DateList2"] = new SelectList(await _dateTest.Get());
            return View(model);
        }
        public async Task<IActionResult> Create(CarDTO model)
        {
            await _car.Create(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(CarDTO model)
        {
            int id = await _car.Update(model);
            return Ok(id);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            await _car.Delete(Id);
            return RedirectToAction("Index");
        }
    }
}

TestingProject.WebApp/Controllers/DateTestController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TestingProject.DTOs;
using TestingProject.IServices;

namespace TestingProject.WebApp.Controllers
{
    public class DateTestController : Controller
    {
        private readonly IDateTestService _dateTest;
        public DateTestController(IDateTestService dateTest)
        {
            _dateTest = dateTest;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dateTest.Get());
        }

        public IActionResult AddEditDate(DateTestDTO model)
        {
            return View(model);
        }
        public async Task<IActionResult> AddDate(DateTestDTO model)
        {
            await _dateTest.Create(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditDate(DateTestDTO model)
        {
            await _dateTest.Update(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteDate(int Id)
        {
            await _dateTest.Delete(Id);
            return RedirectToAction("Index");
        }
    }
}

TestingProject.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TestingProject.WebApp.Models;

namespace TestingProject.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestingProject.WebApp/Controllers/ParameterController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestingProject.DTOs;
using TestingProject.IServices;

namespace TestingProject.WebApp.Controllers
{
    public class ParameterController : Controller
    {
        private readonly IParameterService _parameterService;
        public ParameterController(IParameterService parameterService)
        {
            _parameterService = parameterService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Get()
        {
            IEnumerable<ParameterDTO> parameters = Enumerable.Empty<ParameterDTO>();

            parameters = await _parameterService.Get();

            return Json(parameters);
        }
    }
}

TestingProject.WebApp/Views/Attachment/Index.cshtml
@model TestingProject.DTOs.AttachmentDTO

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div style="margin: 35px">

    <h2>UploadFile</h2>

    <partial name="_AddAttachment" for="@Model" />
    <a class="btn btn-primary" id="modal1" onclick="openModal();">Modal</a>

</div>


@section Scripts{
    <script>
        function openModal() {
            $('#myModal').modal('show');
        }

        function addAtt() {
            var input = $('#files')[0].files[0];
            var files = new FormData();
            files.append('files', input);
            var attachment = $('#addForm').serialize();
            $.ajax({
                url: '/Attachment/AddAttachment',
                type: 'POST',
                data: attachment,
                success: function (data, textStatus, jqXHR) {
                    $.ajax({
                        url: '/Attachment/AddFile',
                        type: 'POST',
                        processData: false,
                        contentType: false,
                        data: files,
                        dataType: 'json'
                    }),
                    console.log(data, textStatus, jqXHR)
                }
            })
        }
    </script>
}

TestingProject.WebApp/Views/Attachment/_AddAttachment.cshtml
@model TestingProject.DTOs.AttachmentDTO


<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
                <div id="addAtt" class="modal-body">
                    <form id="addForm" method="post" enctype="multipart/form-data" asp-controller="Attachment" asp-action="AddAttachment">
                        <div class="form-group">
                            <div class="col-md-10">
                                <p>Upload one or more files using this form:</p>
                                <input asp-for="OriginalFileName" />
                                <input asp-for="FileName" />
                                <input asp-for="FilePath" />
                                <input asp-for="DateAdded" />
                                <input id="files" type="file" name="files" multiple />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="button" value="Upload" onclick="addAtt(this);" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TestingProject.WebApp/Views/Car/AddEditCar.cshtml
@using TestingProject.DTOs
@model TestingProject.DTOs.CarDTO

@{
    IEnumerable<DateTestDTO> dateList = ViewData["DateList"] as IEnumerable<DateTestDTO>;
    IEnumerable<CarDTO> carList = ViewData["CarList"] as IEnumerable<CarDTO>;
    IEnumerable<SelectListItem> listItems = ViewData["DateList2"] as IEnumerable<SelectListItem>;

    string action = "Update";
    if (Model.Id <= 0)
        action = "Create";

    ViewData["Title"] = action;
}

<h1>AddEditCar</h1>

<h4>CarDTO</h4>
<hr />


<div class="row">
    <div class="col-md-6">
        <form id="base" onsubmit="accept(); return false;" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden="hidden">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateId" class="control-label"></label>
                <select asp-for="DateId" asp-items="@(new SelectList(dateList, "Id", "Date1"))" class="control-label">
                    <option value="">Pick one</option>
                </select>
                <span asp-validation-for="DateId" class="text-danger"></span>
            </div>

            <div id="vue">
                <div v-for="param in parameters">
                    <label>{{param}}</label>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" form="base" value= @action class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        var vue = new Vue({
            el: '#vue',
            data: {
                parameters: []
            },
            mounted() {
                this.loadData()
            },
            methods: {
                loadData() {
                    axios({
                        method: 'get',
                        url: '/Parameter/Get',
                    })
                    .then(response => this.parameters = response.data);
                }
            }
        });

        function appendArray(form_data, values, name) {
            if (!values && name)
                form_data.append(name, '');
            else {
                if (typeof values == 'object') {
                    for (key in values) {
                        if (typeof values[key] == 'object')
                            appendArray(form_data, values[key], name + '[' + key + ']');
                        else
                            form_data.append(name + '[' + key + ']', values[key]);
                    }
                } else
                    form_data.append(name, values);
            }

            return form_data;
        }


        function accept() {
            var form = $('form#base')[0];
            var formdata = new FormData(form);

            appendArray(formdata, vue.parameters, 'Parameters');

            axios({
                method: "post",
                url: "/Car/Update",
                data: formdata
            }).then(response => {
                console.log(response.data)
                window.location.href = "/Car/Index"
            }).catch(error => {
                console.log(error.response.data)
            })

            /*
            $.ajax({
                type: 'POST',
                url: '/Car/Update',
                data: formdata,
                processData: false,
                contentType: false,
                success: function (id) {
                    console.log(id);
                    window.location.href = "/Car/Index"
                },
                error: function (jhrx) {
                    console.log(jhrx);
                }
            })
            */

        }
    </script>

}

TestingProject.WebApp/Views/Car/Index.cshtml
@model IEnumerable<TestingProject.DTOs.CarDTO>

@{
    ViewData["Title"] = "CarList";
}

<h1>CarList</h1>

<p>
    <a asp-action="AddEditCar">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateId)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateId)
            </td>
            <td>
                @Html.ActionLink("Update", "AddEditCar", item) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

TestingProject.WebApp/Views/DateTest/AddEditDate.cshtml
@model TestingProject.DTOs.DateTestDTO

@{
    string action = "Update";
    if (Model.Id <= 0)
    {
        action = "Create";
    }

    ViewData["Title"] = action;
}

<h4>DateTestDTO</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action=@action>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden="hidden">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date1" class="control-label"></label>
                <input asp-for="Date1" class="form-control" />
                <span asp-validation-for="Date1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime1" class="control-label"></label>
                <input asp-for="DateTime1" class="form-control" />
                <span asp-validation-for="DateTime1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime2" class="control-label"></label>
                <input asp-for="DateTime2" class="form-control" />
                <span asp-validation-for="DateTime2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value=@action class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingProject.WebApp/Views/DateTest/Index.cshtml
@model IEnumerable<TestingProject.DTOs.DateTestDTO>

@{
    ViewData["Title"] = "DateTest";
}

<h1>DateTest</h1>

<p>
    <a asp-action="AddEditDate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime2)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime2)
            </td>
            <td>
                @Html.ActionLink("Update", "AddEditDate", item) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

TestingProject.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    <div>
        <a class="btn btn-primary" asp-controller="Car" asp-action="Index">Car list</a>
    </div>
    <div>
        <a class="btn btn-primary" asp-controller="DateTest" asp-action="Index">DateTest list</a>
    </div>
    <div>
        <a class="btn btn-primary" asp-controller="Attachment" asp-action="Index">Add attachment</a>
    </div>
</div>

TestingProject.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestingProject.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestingProject.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TestingProject.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>